// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

 import 'firebase_options.dart';
 await Firebase.initializeApp(
   options: DefaultFirebaseOptions.currentPlatform,
 );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDayyWeExJ_aLbZSs6YepCpngMMsOgug8c',
    appId: '1:342398878440:android:0b914e3fa4ca01435fbf5d',
    messagingSenderId: '342398878440',
    projectId: 'blind-danger-detection',
    storageBucket: 'blind-danger-detection.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBba7S3oLoL27BPeC7OuZqAXo0qwVPJWqs',
    appId: '1:342398878440:ios:78b23cf810729a705fbf5d',
    messagingSenderId: '342398878440',
    projectId: 'blind-danger-detection',
    storageBucket: 'blind-danger-detection.appspot.com',
    iosClientId: '342398878440-pkundhijdrn4n3r0qhggp2jpbsq2ddjj.apps.googleusercontent.com',
    iosBundleId: 'com.example.blindDangerDetector',
  );
}
